import React from "react";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Tabs from "@/components/Tabs/Tabs";
import Head from "next/head";
import style from "@/styles/MyProfile.module.scss";
import { GlobalVariables } from "./_app";
import { useContext } from "react";

const MyProfile = () => {
  const { ClientData, setClientData, AvatarCollection } =
    useContext(GlobalVariables);

  return (
    <>
      <Head>
        <title>AnimixPlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        style={{
          position: "static",
          backgroundColor: "#2a2c31",
          background: "url(/FooterBg.jpg)",
        }}
      />
      <main className={style.main}>
        <Tabs Name={`${ClientData.first_name} ${ClientData.last_name}`} />

        <div className={style.Profile}>
          <h1>Profile</h1>

          <div className={style.ProfileBox}>
            <div className={style.col1}>
              <label>First Name</label>
              <input type="text" value={ClientData.first_name} />
              <label>Last Name</label>
              <input type="text" value={ClientData.last_name} />
              <label>User Name</label>
              <input type="text" value={ClientData.username} />
              <label>Email</label>
              <input type="text" value={ClientData.email} />
            </div>
            <div className={style.col2}>
              <img
                src={AvatarCollection[ClientData.profile_image_index]}
                alt=""
              />
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default MyProfile;
